Update dependencies and clean up
bestguy/sveltestrap pull request #310
Opened 2021-06-09 22:05 UTC by mohe2015

https://github.com/bestguy/sveltestrap/issues/309

2021-06-10 02:53 UTC, bestguy requested changes
Thanks, looks great apart from one comment.

2021-06-10 02:53 UTC, bestguy commented on src/Tooltip.svelte
> +  import { createPopper } from '@popperjs/core';
I'm not sure if we can change this, popper has this annoying dependency on node process and this was causing Sveltestrap to break in the svelte.dev repl

Please see this issue: https://github.com/bestguy/sveltestrap/issues/250

2021-06-10 11:17 UTC, mohe2015 commented
I'm still working on some more updates. I will undraft this when it's ready.

2021-06-10 13:44 UTC, mohe2015 commented
@bestguy I think this is ready now. Please thoroughly check that I didn't mess anything up.

2021-06-10 13:45 UTC, mohe2015 commented
Maybe I or you can do a followup to try to update the remaining packages too.

2021-06-11 03:00 UTC, bestguy commented
Thank you for the work! I'll review/merge/release by this weekend.

2021-06-14 15:07 UTC, bestguy approved these changes
LGTM thanks!

2021-06-14 15:07 UTC, merged