chore: upgrade to storybook 7
bestguy/sveltestrap pull request #565
Opened 2023-08-07 19:34 UTC by benmccann

2023-10-12 12:54 UTC, benmccann commented
@bestguy @gary-mycase any chance you might be able to take a look at this one?

2023-10-13 02:19 UTC, bestguy commented
Sure, I'll take a look to review/merge this weekend, thanks for your patience.

2023-10-15 08:19 UTC, kefahi commented
Thanks!
I tried upgrading as outlined above, but couldn't successfully run storybook.
What are the specific steps I need to follow to get the docs folder regenerated with the new version?

2023-10-15 12:59 UTC, benmccann commented
@kefahi can you share what command you ran and what you expected to happen?

2023-10-15 14:13 UTC, kefahi commented
The storybook binary itself was missing, hence running npn run docs/start fails. storybook package that provides the storybook binary was not mentioned in the packages.json file.
I made further tuning to make storybook7 work properly. 

Can be found on this git branch https://github.com/edraj/sveltestrap/tree/storybook7-fixes

The above branch is based on the Svelte4 fixes branch that was prepared earlier. 

I'm good now with both Svelte4 and Storybook7 without any known issues (including passing CI checks).

2023-10-16 00:42 UTC, bestguy requested changes
Hi @benmccann , this is great, thanks.
Looks like one change is needed in my testing.

2023-10-16 00:42 UTC, bestguy commented on package.json
> +    "@storybook/testing-library": "^0.2.0",
Using node 20.8.1, I also needed to add:
`"@storybook/theming": "^7.4.6",` 

otherwise got an error running `npm start` after `npm install`

2023-10-16 05:39 UTC, bestguy approved these changes
Actually, I can easily do a follow on PR to add that missing dep after merge.

2023-10-16 05:39 UTC, merged

2023-10-16 05:46 UTC, bestguy commented
Fixed with #576 
Thanks all!